pipeline {
    agent any
    stages {
        stage('Example Build') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Example Deploy') {
            when {
                allOf {
                    branch 'main'
                    environment name: 'DEPLOY_TO', value: 'main'
                }
            }
            steps {
                echo 'Deploying'
            }
        }
    }
}
